### ISSUE TITLE
Any slugger pleased to make an easy-use image?

### ISSUE THREAD

**Issue by xuze1993** [octave-online/octave-online-server#4]
I've tried the latest version in my Dockfile, things scratch to be ok till a horrible loop happened on making octave after configure.

**Comment by xuze1993** [comment]
> 
> 
> I've tried the latest version in my Dockfile, things scratch to be ok till a horrible loop happened on making octave after configure.

woops,forget it.There seems to be some alternative web interface.

**Comment by sffc** [comment]
Unfortunately it has been difficult to make an "easy-to-use" Docker image, because sandboxing sessions from one another either requires SELinux, which is not supported in Docker, or Docker itself, and last I tried, Docker-in-Docker is not well supported.  In principle, an easy-to-use image could be made if session security were relaxed, which could be OK if deploying in an internal environment but is not recommended for deploying publicly.

**Comment by sffc** [comment]
https://github.com/octave-online/octave-online-server/blob/master/containers/README.md
